# Generated by Django 3.1 on 2021-08-23 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_productlist_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
